const data = {
  products: [
    {
      name: "nike slim shirt",
      slug: "nike-slim-shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirts ",
    },
    {
      name: "adiddas slim shirt",
      slug: "adiddas-slim-shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "adiddas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirts ",
    },
    {
      name: "puma slim shirt",
      slug: "puma-slim-shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirts ",
    },
    {
      name: "lacoste slim shirt",
      slug: "lacoste-slim-shirt",
      category: "shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirts ",
    },
  ],
};

export default data;
